name: Build Assets

on:
  push:
      branches:
        - next-v2
  pull_request:
    branches:
      - next-v2

defaults:
  run:
    working-directory: ./bio
      
jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['14.x']
        os: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: npm install, build
        working-directory: ./bio
        run: |
          npm install
          npm run build --if-present
          
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: copy assets
          path: assets
